# The action is triggered and auto-merges a pull request
# ONLY when it is from a specific user defined below & all checks have passed

name: automerge

on:
  # Events which trigger the action on the pull request
  pull_request:
    types:
      - labeled  # when a label is added to the pull request
  check_suite:
    types:
      - completed  # when all checks for a pull request are completed
      
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          MERGE_FILTER_AUTHOR: "kubescape"  # Specifies the user whose pull request can be auto-merged
